### ISSUE TITLE
Unit tests don't run

### ISSUE THREAD

**Issue by roelvandun** [kanthoney/odata-client#27]
Jest unit tests don't run when odata-client is used. The following error is thrown:
```
You need to run with a version of node that supports ES Modules in the VM API. See https://jestjs.io/docs/ecmascript-modules

      at invariant (node_modules/jest-runtime/build/index.js:2440:11)
      at Object.<anonymous> (node_modules/odata-client/request.js:9:15)
      at Object.<anonymous> (node_modules/odata-client/odata.js:9:17)

```

I am able to run the tests with `NODE_OPTIONS=--experimental-vm-modules jest`, but it would be nice if we didn't have to use a workaround

**Comment by kanthoney** [comment]
That's annoying. I think the problem is that I use [`got`](https://www.npmjs.com/package/got) for web requests, which only supports ESM modules and not the old CommonJS modules. I'm not sure what I can do about that.

**Comment by roelvandun** [comment]
FYI we've worked around this by mocking the entire `odata-client` module with the `__mocks__` approach:

```
class MockOdataClient {
  fn() {
    return this;
  }

  resource() {
    return this;
  }

  or() {
    return this;
  }

  select() {
    return this;
  }

  query() {
    return this;
  }

  get() {
    return {
      body: {
        value: [],
      },
    };
  }
}

module.exports = () => new MockOdataClient();
module.exports.mockOdataClient = MockOdataClient;
```

and then in the unit test file, I require the module like this
```
const { mockOdataClient } = require('odata-client');
```

That way, we also don't need the `NODE_OPTIONS=--experimental-vm-modules` flag for jest.
